(function() {var implementors = {};
implementors["paperclip"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"paperclip/v2/models/enum.Version.html\" title=\"enum paperclip::v2::models::Version\">Version</a>",synthetic:false,types:["paperclip::v2::models::Version"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"paperclip/v2/models/enum.DataType.html\" title=\"enum paperclip::v2::models::DataType\">DataType</a>",synthetic:false,types:["paperclip::v2::models::DataType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"paperclip/v2/models/enum.DataTypeFormat.html\" title=\"enum paperclip::v2::models::DataTypeFormat\">DataTypeFormat</a>",synthetic:false,types:["paperclip::v2::models::DataTypeFormat"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"paperclip/v2/models/enum.ParameterIn.html\" title=\"enum paperclip::v2::models::ParameterIn\">ParameterIn</a>",synthetic:false,types:["paperclip::v2::models::ParameterIn"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"paperclip/v2/models/enum.HttpMethod.html\" title=\"enum paperclip::v2::models::HttpMethod\">HttpMethod</a>",synthetic:false,types:["paperclip::v2::models::HttpMethod"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"paperclip/v2/models/enum.OperationProtocol.html\" title=\"enum paperclip::v2::models::OperationProtocol\">OperationProtocol</a>",synthetic:false,types:["paperclip::v2::models::OperationProtocol"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
