(function() {var implementors = {};
implementors["paperclip"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"paperclip/enum.PaperClipError.html\" title=\"enum paperclip::PaperClipError\">PaperClipError</a>",synthetic:false,types:["paperclip::error::PaperClipError"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"paperclip/v2/codegen/object/struct.ApiObjectImpl.html\" title=\"struct paperclip::v2::codegen::object::ApiObjectImpl\">ApiObjectImpl</a>&lt;'a&gt;",synthetic:false,types:["paperclip::v2::codegen::object::ApiObjectImpl"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"paperclip/v2/codegen/object/struct.ApiObjectBuilder.html\" title=\"struct paperclip::v2::codegen::object::ApiObjectBuilder\">ApiObjectBuilder</a>&lt;'a&gt;",synthetic:false,types:["paperclip::v2::codegen::object::ApiObjectBuilder"]},{text:"impl&lt;'a, 'b&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"paperclip/v2/codegen/object/struct.ApiObjectBuilderImpl.html\" title=\"struct paperclip::v2::codegen::object::ApiObjectBuilderImpl\">ApiObjectBuilderImpl</a>&lt;'a, 'b&gt;",synthetic:false,types:["paperclip::v2::codegen::object::ApiObjectBuilderImpl"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"paperclip/v2/codegen/object/struct.ApiObject.html\" title=\"struct paperclip::v2::codegen::object::ApiObject\">ApiObject</a>",synthetic:false,types:["paperclip::v2::codegen::object::ApiObject"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"paperclip/v2/models/enum.HttpMethod.html\" title=\"enum paperclip::v2::models::HttpMethod\">HttpMethod</a>",synthetic:false,types:["paperclip::v2::models::HttpMethod"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
